# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  pod 'PrayerTimesSwift'
end

target 'PrayerTimesSwift_Example' do
  
  # Pods for PrayerTimesSwift_Example
  shared_pods
  
  target 'PrayerTimesSwift_Tests' do
    inherit! :search_paths
  end
  
end
